safe: false

relative_source: .
destination: dest
username: stdcpp-pl
branch: master

title: C++ PL NB
baseurl: ""
url: "https://www.stdcpp.pl/"
#twitter_username: jekyllrb
github_username:  stdcpp-pl

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin

languages: ["pl", "en"]
exclude_from_localization: []

exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
  - vendor
