safe: false

relative_source: .
destination: dest

title: Polish C++ Standards Committee
email: griwes@griwes.info
description: >-
    Welcome to the website of the Polish National Body at the C++ Standards Committee.
baseurl: ""
url: "https://www.stdcpp.pl/"
#twitter_username: jekyllrb
github_username:  stdcpp-pl

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin

languages: ["pl", "en"]
exclude_from_localization: []

exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
  - vendor
